### ISSUE TITLE
Show/Hide Completed Tasks button

### ISSUE THREAD

**Issue by ekasprzak** [mrvladus/Errands#138]
Hello, I have a lot of completed tasks that I don't want to be deleted.
Would be nice to have a button on a task list that would show/hide completed tasks.

**Comment by mrvladus** [comment]
I'll see how can I implement this.

**Comment by Sesivany** [comment]
Or at least sort completed and uncompleted tasks. Currently it's really difficult to get oriented in the list of the tasks when it's cluttered with completed tasks, you have to look for uncompleted tasks among them and they have no due date info visible in the list either. I know I can delete the completed tasks, but I think the completed tasks should get out of the way automatically.

**Comment by jeena** [comment]
I agree that deleting completed tasks takes away a lot of context which you might have stored there and might want to get back to when you're doing other related tasks. Especially when it comes to subtasks.

**Comment by rubenmvc** [comment]
Hi everyone! I tried to do a simple implementation of this feature but before promoting any branch or merge request, I would like some feedback to know if this properly reflects the enhancement to be developed or if there are some additional aspects to consider.

As a side note, this is my first attempt to do a contribution to an app I really like, so thanks in advance for the support!

[Screencast from 2024-03-10 23-44-17.webm](https://github.com/mrvladus/Errands/assets/32852022/bf0700c2-2c1c-4d79-9b96-5cca66735939)

**Comment by rubenmvc** [comment]
Hi everyone! I tried to do a simple implementation of this feature but before promoting any branch or merge request, I would like some feedback to know if this properly reflects the enhancement to be developed or if there are some additional aspects to consider.

For example, I'm not sure if this option should affect all the lists at the same time or only the ones that you selected as you can see here.

As a side note, this is my first attempt to do a code contribution to an app I really like, so thanks in advance for your help!

[Screencast from 2024-03-10 23-44-17.webm](https://github.com/mrvladus/Errands/assets/32852022/bf0700c2-2c1c-4d79-9b96-5cca66735939)

**Comment by Anthony-Fiddes** [comment]
Per list is definitely more flexible (and the way you implemented it looks great too!).

When I subscribed to this issue, I just wanted any way to hide completed tasks at all. I think I initially imagined it being a global toggle, but I also don't use more than like 5 lists, so a solution like is shown in the video would still be good for me.

**Comment by mrvladus** [comment]
@rubenmvc Hi! It's really cool! I'm currently working on redesign of task lists using ListBox so I can dynamically sort them or show/hide completed tasks. I have some perfomance issues with it though. But probably it would be easy to fix. All current progress is on the `dev` branch. I didn't write databbase migration code yet, so you need to delete `data.db` file at data directory first to run it.

**Comment by rubenmvc** [comment]
@mrvladus Thanks for the feedback! If you're already working on that redesign based on main branch, but I suppose your solution will be even better so I'll save mine locally (just in case) and try instead the current work on `dev` branch to see what is the status and if something could be improved.

**Comment by rubenmvc** [comment]
@mrvladus Thanks for the feedback! If you're already working on that redesign I suppose your solution will be even better so I'll save mine locally (just in case, it was based on `main`) and try instead the current work on `dev` branch to see what is the status and if something could be improved.

The problem is that I tried to find that `data.db` file at the "data" directory and I couldn't find anything. Just to be sure, I deleted the entire folder and clone the repository again and I have the same issue, so I can't find where is the db file.

![Screenshot from 2024-03-11 15-29-28](https://github.com/mrvladus/Errands/assets/32852022/da123d87-cc2d-4667-81e0-0769e4d12190)

**Comment by mrvladus** [comment]
@rubenmvc sorry, I wasn't clear. File at ~/.var/app/io.github.mrvladus.List/data/errands/data.db

**Comment by rubenmvc** [comment]
@mrvladus Don't worry, thanks for the clarification! I deleted the DB and tested the most recent changes from `dev` and I can confirm the small delay/freeze when completing tasks and refreshing the list. Let's see if I can identify what could be the root cause and try to fix it.

Aside of that, I also tried to re-implement the same idea from my first message over your new implementation in case that we want that functionality, as you can see here. I don't know if in your redesign you wanted to achieve this in other way or my suggestion fits properly.

[Screencast from 2024-03-11 19-47-28.webm](https://github.com/mrvladus/Errands/assets/32852022/1f005222-588c-4ec2-88f1-a7d196677127)

Just to tell you, but basically what I did was a similar approach to the "Delete Completed Tasks" behavior: loop over the task list and when a task (or sub-task) is complete, depending on the toggle status I change the visibility of that item. If it is OK for you, I could push my branch in case that you want to check it. 

Thanks in advance! :)

**Comment by mrvladus** [comment]
@rubenmvc you can make a MR. And I have found the issue with lag, it's in sql code, so no problems with ListBox. Just need to do some refactoring.

**Comment by mrvladus** [comment]
@rubenmvc you need to fork this repo on GitHub, then clone your fork, make changes there, and push them. After this you can make a pull request on GitHub.

**Comment by rubenmvc** [comment]
@mrvladus Thanks for your help, it was my fault because somehow I skip that critical step and I didn't notice. You can review it and merge it if you want :)

One more thing, just to know for future contributions: when implementing new features like this, should I provide also some translations, in this case for the new button (I could add them to this PR)? Or it is better to do it later as an additional MR? (from me or other contributors)

**Comment by mrvladus** [comment]
@rubenmvc trasnslations are managed separately. I will use Weblate in the next release.

**Comment by rubenmvc** [comment]
@mrvladus Sorry for the delay, I have read your comments on the PR and also you've already done some small tweaks over my implementation. I've checked them and it's cleaner and improved, thanks! At least we have a first functional version :)

As I understood from the PR, the next step could be the inclusion of this functionality in the preferences menu at the task list headerbar. I saw that "Show Completed Tasks" switch there, so I suppose that would work as a global preference that overrides the current toggle over each task list, or am I wrong?

**Comment by mrvladus** [comment]
@rubenmvc I'll remove that preference, because I'm going to make it per-list setting.

**Comment by major-mayer** [comment]
Does this PR also include the functionality to hide tasks that have not started yet?
Or should I create a separate issue for this?

**Comment by mrvladus** [comment]
@major-mayer What do you mean by 'have not started'? If you talking about showing only tasks for today, then I added Today page with tasks planned for today. 
![Снимок экрана от 2024-04-05 15-11-04](https://github.com/mrvladus/Errands/assets/64690334/7bdf607e-a577-433d-bd35-516e05a3decb)

**Comment by mrvladus** [comment]
Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)

**Comment by major-mayer** [comment]
> Added in [46.0](https://github.com/mrvladus/Errands/releases/tag/46.0)

Not sure if that's exactly doing what I have wished.
The today page for me is only showing the tasks that are due for today, but most of my tasks don't have a due date, so it's mostly empty.
The task list page shows all tasks that haven't been completed, including the ones that haven't started yet.
I don't see an option to hide those tasks.

Should I create a separate feature request or did i miss something?

**Comment by mrvladus** [comment]
@major-mayer If I undestood correctly, you want to show tasks inside Today page that have start date and don't have due date (meaning currently started tasks) ?

**Comment by major-mayer** [comment]
I'm not quite sure if tasks that have a start date and don't have a due date would be suitable for the today page, because it's not due today.
I'm even less sure about tasks that don't have a start date at all.

But it would be really nice to have an option in the task list page (!) (so when you click on a specific task list an look at the tasks there) that hides tasks that have a start date and this date is in the future.
Those tasks are probably not relevant in most cases.

**Comment by major-mayer** [comment]
@mrvladus Anything new about this?
