### ISSUE TITLE
Use Nextcloud credentials from GNOME Online Accounts

### ISSUE THREAD

**Issue by strugee** [mrvladus/Errands#144]
I'm already signed into Nextcloud in GNOME Control Center's Online Accounts settings pane - Errands should pick these credentials up and Just Work(tm) if I select Nextcloud in the settings. (Maybe even automatically turn on sync for Nextcloud? Or prompt the user to turn it on? Not sure.)

Nextcloud doesn't have a "Tasks" or "Todo" slider in the settings interface, so I assume it does not implement the GOA `Todo` interface. But I think you should be able to get the password from [`GetPassword()` over D-Bus](https://developer-old.gnome.org/goa/stable/gdbus-org.gnome.OnlineAccounts.PasswordBased.html).

**Comment by benmordecai** [comment]
A bit of feedback on this topic - the entire reason I am using Errands rather than Gnome Todo is because it allows Nextcloud sync without using Gnome Online accounts, as I use KDE plasma and there is no straightforward way to connect an online account besides using Gnome online accounts which does not work outside of using Gnome as your Desktop environment. So if this feature is added I would humbly request it not break syncing for those people not using Gnome Desktop Environment.

**Comment by mrvladus** [comment]
@benmordecai don't worry, if I add this, it  will only check for online accounts and fill out the credentials. I didn't use GOA in the first place because of that very reason - to make sync accessible to all desktops.

**Comment by mrvladus** [comment]
Added in [45.1.6](https://github.com/mrvladus/Errands/releases/tag/45.1.6)
