### ISSUE TITLE
[Feature Request] Ability to use Errands on WSL

### ISSUE THREAD

**Issue by benmordecai** [mrvladus/Errands#147]
This is perhaps a stretch, but this issue is more to introduce the idea and make known the desire.

Right now there is no good caldav based task manager for Windows that isn't a part of some clunky email software. Due to the fact Errands is flatpak-only and there is kludgy or non-existent dbus support on Windows Subsystem for Linux, it makes it difficult to use flatpak based software. It would be nice if there was a good way to use Errands on WSL

**Comment by mrvladus** [comment]
Yeah... Probably the better place for this issue is flatpak's repo. As for Errands, and for me personally, I'm not using Windows at all for 4 years now and until flatpak works with WSL I'm afraid it will be not possible to run Errands in it, unless building and installing from source inside WSL environment.

**Comment by benmordecai** [comment]
Understandable. If I had any say in the matter I would ditch windows entirely myself.
