### ISSUE TITLE
Add labels / tags next to task name

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#160]
Hi, the task items in the list are already very large. It would be handy to use that space and display labels for detailed information about the task (e.g. tags, dates, prios), possibly as a suffix or in a second line below the name.

Planify for example does this quite well in my opinion, like this:
![grafik](https://github.com/mrvladus/Errands/assets/43520007/47c53801-69ee-41b8-b19a-0035e72cdb2c)

On the other hand, if you want to stick to the minimalist approach, I'd  suggest to add "..." or something like to the task, to show that there's more to discover in the details.

**Comment by mrvladus** [comment]
I'll need to think about it, how to do it without cluttering task widget

**Comment by Julian4711** [comment]
This is how Nextcloud Tasks does it:

![grafik](https://github.com/mrvladus/Errands/assets/43520007/f0b8f9c9-59de-4088-b8db-4815525ae2b9)

**Comment by jeena** [comment]
Actually I was also thinking that I did something wrong with the tags because they didn't show up in the list anywhere.

**Comment by CristianKerr** [comment]
This is very important, to see tags and be able to show all tasks with same tags (e.g. sidepanel tags list). It could even be optional feature to be turned on/off in settings if you don't want to lose the uncluttered look. But for me this is a must have if I am to work with tasks effectively :) 
Otherwise I really like your app and it even works well with EteSync.

**Comment by mrvladus** [comment]
I reworked tags system, now tags will be showing under task title. Will be available in the next release.
