### ISSUE TITLE
Priority flags

### ISSUE THREAD

**Issue by wada3n** [mrvladus/Errands#205]
Hi,

Any chance to add the ability to add priority flags to tasks.

Currently, Errands uses numbers to indicate task priority. However, I find this system to be somewhat confusing and counterintuitive.

Numbers are inherently subjective and can vary depending on the individual user and their specific needs.

Additionally, numbers can be difficult to remember and track, especially when dealing with a large number of tasks.

I believe that a system of priority flags would be a much more effective way to prioritize tasks.

Flags could be assigned to tasks based on their importance, urgency, or other criteria.

For example, a task that is both important and urgent could be assigned a red flag, while a task that is less important and less urgent could be assigned a yellow flag...

This system would make it much easier for users to quickly identify and prioritize their tasks.

Thanks again for your work on this wonderful app!

**Comment by Eurbaix** [comment]
Since Errands use Nextcloud Tasks for sync, I think it should maintain the compatibility with the Tasks app in Nextcloud by providing the current fine granularity of priority from 0 to 9. A text (High/Medium/Low) could be shown beside the number though (like on Nextcloud Tasks) to make the interpretation easier.

As for the Urgent vs Important, the combination of Priority and Color can already be used to manage tasks on 2 different scales - Not Urgent to Urgent and Not Important to Important - in Errands.

Last, Nextcloud Tasks has a somewhat counter intuitive interpretation of the priority value (1-4=High; 6=Medium; 7-9=Low) but, since some people (incl. me) manage tasks both in Errands and Nextcloud Tasks, Errands should keep that interpretation of the priority scale so it's not confusing when switching between Errands and Nextcloud Tasks.

**Comment by mrvladus** [comment]
Implemented it on `dev` branch, will be available in the next release.
