### ISSUE TITLE
No Task colors in export

### ISSUE THREAD

**Issue by ColbyB722** [mrvladus/Errands#262]
Hello Mrvladus, please add the colors of tasks to the export.ics file. 

I had thought the colors of tasks seemed to disappear when imported but they were not included in the export file. 

And thanks for the awesome work you do on this program!

**Comment by mrvladus** [comment]
Added in 8975220ffef49a7b508511fd2bd011d06e5b6b8b. But colors only will be visible to Errands, because it's custom property `X-ERRANDS-COLOR`. There is also `X-APPLE-CALENDAR-COLOR` for task lits that Nextcloud supports, but it's using HEX colors, while I just use 7 hard-coded color names. I need to figure that out for task lists. Until then custom propery will do fine.
