### ISSUE TITLE
Task improvements

### ISSUE THREAD

**Issue by M00NJ** [mrvladus/Errands#278]
I have two small suggestions to improve the task UX:

**1. Automatically mark task as completed if all sub-tasks are done**

![Screenshot from 2024-05-15 11-03-49](https://github.com/mrvladus/Errands/assets/82398591/da26a365-8f1d-4b2d-b141-19b6b4974a9c)
In this example all the sub-tasks have been completed, so the main task should be checked as well.

**2. Only count sub-tasks**

![Screenshot from 2024-05-15 11-20-48](https://github.com/mrvladus/Errands/assets/82398591/eafe7620-139e-4b25-b908-84ab8fc26181)
If tasks are automatically completed when all the sub-tasks are done, then only the sub-tasks should be counted. In this example `fruit` doesn't need to be counted as a separate task, because it will be completed when I've bought **_apples_** and _**bananas**_. The same goes for the `Buy groceries` item. So the number of tasks in this list should be `4` instead of `6`. In a long list that is organized with many sub-tasks, the lager number can be intimidating/demotivating.

**Comment by mrvladus** [comment]
> 1. Automatically mark task as completed if all sub-tasks are done

I decided not to do that on purpose. Because if all sub-tasks are completed and task in marked completed - it will go down the list, and if you want to add new sub-tasks to that task, you need to un-complete it first then add new sub-tasks. For example I create top-level tasks as permanent categories in task lists and never complete them, but only their sub-tasks, so I can then add new sub-tasks to them.

> 2. Only count sub-tasks

This would be very confusing.

**Comment by M00NJ** [comment]
I see. I guess these could be prefrences. But if it's not something you would like in Errands, feel free to close this :)
