### ISSUE TITLE
Option to save and restore window position and size

### ISSUE THREAD

**Issue by Julian4711** [mrvladus/Errands#73]
that would be nice :)

**Comment by mrvladus** [comment]
Window size is already saved and restored. But window position... GTK4 removed all window position API because it is the job of compositor. There is some work to support it on wayland [here](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/247). And it is possible to set it on X11, but i'm not gonna do that, because everything is moving to wayland and I didn't used X11 for a year now, 'cause wayland is working perfectly fine. So that is it :)
